### ISSUE TITLE
Cannot run multiple instances of Angora.

### ISSUE THREAD

**Issue by zhanggenex** [AngoraFuzzer/Angora#105]
I succesfully started one instance of angora. But when I started the second one, the following error message came out:

> thread 'main' panicked at 'Output directory has existed!: Os { code: 17, kind: AlreadyExists, message: "File exists" }', src/libcore/result.rs:1188:5
> stack backtrace:
>    0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
>    1: core::fmt::write
>    2: std::io::Write::write_fmt
>    3: std::panicking::default_hook::{{closure}}
>    4: std::panicking::default_hook
>    5: std::panicking::rust_panic_with_hook
>    6: rust_begin_unwind
>    7: core::panicking::panic_fmt
>    8: core::result::unwrap_failed
>    9: angora::fuzz_main::fuzz_main
>   10: fuzzer::main
>   11: std::rt::lang_start::{{closure}}
>   12: std::panicking::try::do_call
>   13: __rust_maybe_catch_panic
>   14: std::rt::lang_start_internal
>   15: main
>   16: __libc_start_main
>   17: _start
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by DataCorrupted** [comment]
This error msg locates back to `fuzz_main.rs:130`. 

This is not a bug but a feature. 
Angora won't allow you to have multiple fuzzers dumping to the same directory. Please try `-o <dir>` to specify different output directories for different fuzzers to prevent this.
