### ISSUE TITLE
xpdf building error

### ISSUE THREAD

**Issue by lmrs2** [AngoraFuzzer/Angora#30]
steps to reproduce:

wget https://xpdfreader-dl.s3.amazonaws.com/xpdf-4.00.tar.gz
tar xvf xpdf-4.00
cd xpdf-4.00
mkdir build && cd build
LD=$ANGORA_DIR/angora-clang++ CC=$ANGORA_DIR/angora-clang CXX=$ANGORA_DIR/angora-clang++ cmake -DCMAKE_BUILD_TYPE=Release ..

USE_TRACK=1 make -j16​

it fails with the following error below. Note this is C++ code, not C. I tried with gllvm and got similar problems...

Note that USE_FAST compiles properly.

CMakeFiles/pdftopng.dir/pdftopng.cc.o: In function `setupPNG(png_struct_def**, png_info_struct**, _IO_FILE*, int, int, double, SplashBitmap*)':
/path/to/xpdf-4.00_angora/xpdf/pdftopng.cc:282: undefined reference to `dfs$png_create_write_struct'
/path/to/xpdf-4.00_angora/xpdf/pdftopng.cc:284: undefined reference to `dfs$png_create_info_struct'
/path/to/xpdf-4.00_angora/xpdf/pdftopng.cc:290: undefined reference to `dfs$png_init_io'
/path/to/xpdf-4.00_angora/xpdf/pdftopng.cc:291: undefined reference to `dfs$png_set_IHDR'
/path/to/xpdf-4.00_angora/xpdf/pdftopng.cc:301: undefined reference to `dfs$png_set_bKGD'
/path/to/xpdf-4.00_angora/xpdf/pdftopng.cc:304: undefined reference to `dfs$png_set_pHYs'
/path/to/xpdf-4.00_angora/xpdf/pdftopng.cc:306: undefined reference to `dfs$png_write_info'
CMakeFiles/pdftopng.dir/pdftopng.cc.o: In function `writePNGData(png_struct_def*, SplashBitmap*)':
/path/to/xpdf-4.00_angora/xpdf/pdftopng.cc:346: undefined reference to `dfs$png_write_row'
/path/to/xpdf-4.00_angora/xpdf/pdftopng.cc:327: undefined reference to `dfs$png_write_row'
/path/to/xpdf-4.00_angora/xpdf/pdftopng.cc:340: undefined reference to `dfs$png_write_row'
CMakeFiles/pdftopng.dir/pdftopng.cc.o: In function `finishPNG(png_struct_def**, png_info_struct**)':
/path/to/xpdf-4.00_angora/xpdf/pdftopng.cc:358: undefined reference to `dfs$png_write_end'
/path/to/xpdf-4.00_angora/xpdf/pdftopng.cc:359: undefined reference to `dfs$png_destroy_write_struct'
CMakeFiles/pdftohtml.dir/HTMLGen.cc.o: In function `HTMLGen::convertPage(int, char const*, int (*)(void*, char const*, int), void*, int (*)(void*, char const*, int), void*)':
/path/to/xpdf-4.00_angora/xpdf/HTMLGen.cc:271: undefined reference to `dfs$png_create_write_struct'
/path/to/xpdf-4.00_angora/xpdf/HTMLGen.cc:273: undefined reference to `dfs$png_create_info_struct'
/path/to/xpdf-4.00_angora/xpdf/HTMLGen.cc:281: undefined reference to `dfs$png_set_write_fn'
/path/to/xpdf-4.00_angora/xpdf/HTMLGen.cc:282: undefined reference to `dfs$png_set_IHDR'
/path/to/xpdf-4.00_angora/xpdf/HTMLGen.cc:285: undefined reference to `dfs$png_write_info'
/path/to/xpdf-4.00_angora/xpdf/HTMLGen.cc:288: undefined reference to `dfs$png_write_row'
/path/to/xpdf-4.00_angora/xpdf/HTMLGen.cc:291: undefined reference to `dfs$png_write_end'
/path/to/xpdf-4.00_angora/xpdf/HTMLGen.cc:292: undefined reference to `dfs$png_destroy_write_struct'
CMakeFiles/pdftohtml.dir/HTMLGen.cc.o: In function `pngWriteFunc(png_struct_def*, unsigned char*, unsigned long)':
/path/to/xpdf-4.00_angora/xpdf/HTMLGen.cc:238: undefined reference to `dfs$png_get_progressive_ptr'
../splash/libsplash.a(SplashFTFontEngine.cc.o): In function `SplashFTFontEngine':
/path/to/xpdf-4.00_angora/splash/SplashFTFontEngine.cc:65: undefined reference to `dfs$FT_Library_Version'
../splash/libsplash.a(SplashFTFontEngine.cc.o): In function `SplashFTFontEngine::init(int, unsigned int)':
/path/to/xpdf-4.00_angora/splash/SplashFTFontEngine.cc:73: undefined reference to `dfs$FT_Init_FreeType'
../splash/libsplash.a(SplashFTFontEngine.cc.o): In function `~SplashFTFontEngine':
/path/to/xpdf-4.00_angora/splash/SplashFTFontEngine.cc:80: undefined reference to `dfs$FT_Done_FreeType'
../splash/libsplash.a(SplashFTFontFile.cc.o): In function `SplashFTFontFile::loadType1Font(SplashFTFontEngine*, SplashFontFileID*, SplashFontType, char*, int, char const**)':
/path/to/xpdf-4.00_angora/splash/SplashFTFontFile.cc:47: undefined reference to `dfs$FT_New_Face'
/path/to/xpdf-4.00_angora/splash/SplashFTFontFile.cc:55: undefined reference to `dfs$FT_Get_Name_Index'
../splash/libsplash.a(SplashFTFontFile.cc.o): In function `SplashFTFontFile::loadCIDFont(SplashFTFontEngine*, SplashFontFileID*, SplashFontType, char*, int, int*, int)':
/path/to/xpdf-4.00_angora/splash/SplashFTFontFile.cc:85: undefined reference to `dfs$FT_New_Face'
../splash/libsplash.a(SplashFTFontFile.cc.o): In function `SplashFTFontFile::loadTrueTypeFont(SplashFTFontEngine*, SplashFontFileID*, SplashFontType, char*, int, int, int*, int)':
/path/to/xpdf-4.00_angora/splash/SplashFTFontFile.cc:117: undefined reference to `dfs$FT_New_Face'
../splash/libsplash.a(SplashFTFontFile.cc.o): In function `~SplashFTFontFile':
/path/to/xpdf-4.00_angora/splash/SplashFTFontFile.cc:155: undefined reference to `dfs$FT_Done_Face'
../splash/libsplash.a(SplashFTFontEngine.cc.o): In function `SplashFTFontEngine':
/path/to/xpdf-4.00_angora/splash/SplashFTFontEngine.cc:65: undefined reference to `dfs$FT_Library_Version'
../splash/libsplash.a(SplashFTFontEngine.cc.o): In function `SplashFTFontEngine::init(int, unsigned int)':
/path/to/xpdf-4.00_angora/splash/SplashFTFontEngine.cc:73: undefined reference to `dfs$FT_Init_FreeType'
../splash/libsplash.a(SplashFTFontEngine.cc.o): In function `~SplashFTFontEngine':
/path/to/xpdf-4.00_angora/splash/SplashFTFontEngine.cc:80: undefined reference to `dfs$FT_Done_FreeType'
../splash/libsplash.a(SplashFTFontFile.cc.o): In function `SplashFTFontFile::loadType1Font(SplashFTFontEngine*, SplashFontFileID*, SplashFontType, char*, int, char const**)':
/path/to/xpdf-4.00_angora/splash/SplashFTFontFile.cc:47: undefined reference to `dfs$FT_New_Face'
/path/to/xpdf-4.00_angora/splash/SplashFTFontFile.cc:55: undefined reference to `dfs$FT_Get_Name_Index'
../splash/libsplash.a(SplashFTFontFile.cc.o): In function `SplashFTFontFile::loadCIDFont(SplashFTFontEngine*, SplashFontFileID*, SplashFontType, char*, int, int*, int)':
/path/to/xpdf-4.00_angora/splash/SplashFTFontFile.cc:85: undefined reference to `dfs$FT_New_Face'
../splash/libsplash.a(SplashFTFontFile.cc.o): In function `SplashFTFontFile::loadTrueTypeFont(SplashFTFontEngine*, SplashFontFileID*, SplashFontType, char*, int, int, int*, int)':
/path/to/xpdf-4.00_angora/splash/SplashFTFontFile.cc:117: undefined reference to `dfs$FT_New_Face'
../splash/libsplash.a(SplashFTFontFile.cc.o): In function `~SplashFTFontFile':
/path/to/xpdf-4.00_angora/splash/SplashFTFontFile.cc:155: undefined reference to `dfs$FT_Done_Face'
../splash/libsplash.a(SplashFTFont.cc.o): In function `SplashFTFont':
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:56: undefined reference to `dfs$FT_New_Size'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:64: undefined reference to `dfs$FT_Set_Pixel_Sizes'
../splash/libsplash.a(SplashFTFont.cc.o): In function `SplashFTFont::makeGlyph(int, int, int, SplashGlyphBitmap*)':
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:239: undefined reference to `dfs$FT_Set_Transform'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:271: undefined reference to `dfs$FT_Load_Glyph'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:276: undefined reference to `dfs$FT_Load_Glyph'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:280: undefined reference to `dfs$FT_Render_Glyph'
../splash/libsplash.a(SplashFTFont.cc.o): In function `SplashFTFont::getGlyphPath(int)':
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:340: undefined reference to `dfs$FT_Set_Transform'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:351: undefined reference to `dfs$FT_Load_Glyph'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:355: undefined reference to `dfs$FT_Load_Glyph'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:360: undefined reference to `dfs$FT_Get_Glyph'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:366: undefined reference to `dfs$FT_Outline_Decompose'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:371: undefined reference to `dfs$FT_Done_Glyph'
../splash/libsplash.a(SplashFTFont.cc.o): In function `SplashFTFont':
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:56: undefined reference to `dfs$FT_New_Size'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:64: undefined reference to `dfs$FT_Set_Pixel_Sizes'
../splash/libsplash.a(SplashFTFont.cc.o): In function `SplashFTFont::makeGlyph(int, int, int, SplashGlyphBitmap*)':
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:239: undefined reference to `dfs$FT_Set_Transform'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:271: undefined reference to `dfs$FT_Load_Glyph'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:276: undefined reference to `dfs$FT_Load_Glyph'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:280: undefined reference to `dfs$FT_Render_Glyph'
../splash/libsplash.a(SplashFTFont.cc.o): In function `SplashFTFont::getGlyphPath(int)':
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:340: undefined reference to `dfs$FT_Set_Transform'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:351: undefined reference to `dfs$FT_Load_Glyph'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:355: undefined reference to `dfs$FT_Load_Glyph'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:360: undefined reference to `dfs$FT_Get_Glyph'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:366: undefined reference to `dfs$FT_Outline_Decompose'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:371: undefined reference to `dfs$FT_Done_Glyph'
../splash/libsplash.a(SplashFTFontEngine.cc.o): In function `SplashFTFontEngine':
/path/to/xpdf-4.00_angora/splash/SplashFTFontEngine.cc:65: undefined reference to `dfs$FT_Library_Version'
../splash/libsplash.a(SplashFTFontEngine.cc.o): In function `SplashFTFontEngine::init(int, unsigned int)':
/path/to/xpdf-4.00_angora/splash/SplashFTFontEngine.cc:73: undefined reference to `dfs$FT_Init_FreeType'
../splash/libsplash.a(SplashFTFontEngine.cc.o): In function `~SplashFTFontEngine':
/path/to/xpdf-4.00_angora/splash/SplashFTFontEngine.cc:80: undefined reference to `dfs$FT_Done_FreeType'
../splash/libsplash.a(SplashFTFontFile.cc.o): In function `SplashFTFontFile::loadType1Font(SplashFTFontEngine*, SplashFontFileID*, SplashFontType, char*, int, char const**)':
/path/to/xpdf-4.00_angora/splash/SplashFTFontFile.cc:47: undefined reference to `dfs$FT_New_Face'
/path/to/xpdf-4.00_angora/splash/SplashFTFontFile.cc:55: undefined reference to `dfs$FT_Get_Name_Index'
../splash/libsplash.a(SplashFTFontFile.cc.o): In function `SplashFTFontFile::loadCIDFont(SplashFTFontEngine*, SplashFontFileID*, SplashFontType, char*, int, int*, int)':
/path/to/xpdf-4.00_angora/splash/SplashFTFontFile.cc:85: undefined reference to `dfs$FT_New_Face'
../splash/libsplash.a(SplashFTFontFile.cc.o): In function `SplashFTFontFile::loadTrueTypeFont(SplashFTFontEngine*, SplashFontFileID*, SplashFontType, char*, int, int, int*, int)':
/path/to/xpdf-4.00_angora/splash/SplashFTFontFile.cc:117: undefined reference to `dfs$FT_New_Face'
../splash/libsplash.a(SplashFTFontFile.cc.o): In function `~SplashFTFontFile':
/path/to/xpdf-4.00_angora/splash/SplashFTFontFile.cc:155: undefined reference to `dfs$FT_Done_Face'
../splash/libsplash.a(SplashFTFont.cc.o): In function `SplashFTFont':
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:56: undefined reference to `dfs$FT_New_Size'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:64: undefined reference to `dfs$FT_Set_Pixel_Sizes'
../splash/libsplash.a(SplashFTFont.cc.o): In function `SplashFTFont::makeGlyph(int, int, int, SplashGlyphBitmap*)':
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:239: undefined reference to `dfs$FT_Set_Transform'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:271: undefined reference to `dfs$FT_Load_Glyph'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:276: undefined reference to `dfs$FT_Load_Glyph'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:280: undefined reference to `dfs$FT_Render_Glyph'
../splash/libsplash.a(SplashFTFont.cc.o): In function `SplashFTFont::getGlyphPath(int)':
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:340: undefined reference to `dfs$FT_Set_Transform'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:351: undefined reference to `dfs$FT_Load_Glyph'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:355: undefined reference to `dfs$FT_Load_Glyph'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:360: undefined reference to `dfs$FT_Get_Glyph'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:366: undefined reference to `dfs$FT_Outline_Decompose'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:371: undefined reference to `dfs$FT_Done_Glyph'
../splash/libsplash.a(SplashFTFontEngine.cc.o): In function `SplashFTFontEngine':
/path/to/xpdf-4.00_angora/splash/SplashFTFontEngine.cc:65: undefined reference to `dfs$FT_Library_Version'
../splash/libsplash.a(SplashFTFontEngine.cc.o): In function `SplashFTFontEngine::init(int, unsigned int)':
/path/to/xpdf-4.00_angora/splash/SplashFTFontEngine.cc:73: undefined reference to `dfs$FT_Init_FreeType'
../splash/libsplash.a(SplashFTFontEngine.cc.o): In function `~SplashFTFontEngine':
/path/to/xpdf-4.00_angora/splash/SplashFTFontEngine.cc:80: undefined reference to `dfs$FT_Done_FreeType'
../splash/libsplash.a(SplashFTFontFile.cc.o): In function `SplashFTFontFile::loadType1Font(SplashFTFontEngine*, SplashFontFileID*, SplashFontType, char*, int, char const**)':
/path/to/xpdf-4.00_angora/splash/SplashFTFontFile.cc:47: undefined reference to `dfs$FT_New_Face'
/path/to/xpdf-4.00_angora/splash/SplashFTFontFile.cc:55: undefined reference to `dfs$FT_Get_Name_Index'
../splash/libsplash.a(SplashFTFontFile.cc.o): In function `SplashFTFontFile::loadCIDFont(SplashFTFontEngine*, SplashFontFileID*, SplashFontType, char*, int, int*, int)':
/path/to/xpdf-4.00_angora/splash/SplashFTFontFile.cc:85: undefined reference to `dfs$FT_New_Face'
../splash/libsplash.a(SplashFTFontFile.cc.o): In function `SplashFTFontFile::loadTrueTypeFont(SplashFTFontEngine*, SplashFontFileID*, SplashFontType, char*, int, int, int*, int)':
/path/to/xpdf-4.00_angora/splash/SplashFTFontFile.cc:117: undefined reference to `dfs$FT_New_Face'
../splash/libsplash.a(SplashFTFontFile.cc.o): In function `~SplashFTFontFile':
/path/to/xpdf-4.00_angora/splash/SplashFTFontFile.cc:155: undefined reference to `dfs$FT_Done_Face'
../splash/libsplash.a(SplashFTFont.cc.o): In function `SplashFTFont':
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:56: undefined reference to `dfs$FT_New_Size'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:64: undefined reference to `dfs$FT_Set_Pixel_Sizes'
../splash/libsplash.a(SplashFTFont.cc.o): In function `SplashFTFont::makeGlyph(int, int, int, SplashGlyphBitmap*)':
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:239: undefined reference to `dfs$FT_Set_Transform'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:271: undefined reference to `dfs$FT_Load_Glyph'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:276: undefined reference to `dfs$FT_Load_Glyph'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:280: undefined reference to `dfs$FT_Render_Glyph'
../splash/libsplash.a(SplashFTFont.cc.o): In function `SplashFTFont::getGlyphPath(int)':
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:340: undefined reference to `dfs$FT_Set_Transform'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:351: undefined reference to `dfs$FT_Load_Glyph'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:355: undefined reference to `dfs$FT_Load_Glyph'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:360: undefined reference to `dfs$FT_Get_Glyph'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:366: undefined reference to `dfs$FT_Outline_Decompose'
/path/to/xpdf-4.00_angora/splash/SplashFTFont.cc:371: undefined reference to `dfs$FT_Done_Glyph'
[ 80%] Built target pdfdetach
[ 82%] Built target pdfimages
[ 83%] Built target pdfinfo
[ 84%] Built target pdffonts
[ 86%] Built target pdftotext
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [xpdf/pdftoppm] Error 1
make[2]: *** [xpdf/pdftopng] Error 1
make[1]: *** [xpdf/CMakeFiles/pdftoppm.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [xpdf/CMakeFiles/pdftopng.dir/all] Error 2
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [xpdf/pdftohtml] Error 1
make[1]: *** [xpdf/CMakeFiles/pdftohtml.dir/all] Error 2
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [xpdf/pdftops] Error 1
make[1]: *** [xpdf/CMakeFiles/pdftops.dir/all] Error 2
make: *** [all] Error 2

**Comment by spinpx** [comment]
I use 
```
cmake -DCMAKE_C_COMPILER=/home/chenpeng/angora/bin/angora-clang     \
      -DCMAKE_CXX_COMPILER=/home/chenpeng/angora/bin/angora-clang++ \
      -DBUILD_SHARED_LIBS=OFF ..
```

to compile and it works.
