### ISSUE TITLE
Could you provide stable release?

### ISSUE THREAD

**Issue by zhangysh1995** [AngoraFuzzer/Angora#35]
I think it will be better for testing purpose.... #3 #1

**Comment by zhangysh1995** [comment]
> I don't know what you meaning. We have open source the code.

Because we have different environment, and it is difficult to troubleshooting the source code. And the source code in master branch is always changing. Please check for other open source projects such [openssl](https://github.com/openssl/openssl/releases), which have release stable code.

**Comment by spinpx** [comment]
Thanks for your suggestion. You can check the git commit version you are using for troubleshooting.

**Comment by zhangysh1995** [comment]
I tried the current code of `master branch` on `Ubuntu 16.04`, and it works well. Maybe you could release it.
