### ISSUE TITLE
llvm_mode/libcxx/compile.sh fails

### ISSUE THREAD

**Issue by adrianherrera** [AngoraFuzzer/Angora#65]
Hi there,

I am trying to compile a C++ driver similar to [afl_driver.cpp](https://github.com/llvm-mirror/compiler-rt/blob/release_70/lib/fuzzer/afl/afl_driver.cpp) so that I can use Angora on Google's [test suite](https://github.com/google/fuzzer-test-suite), but I am getting issues regarding C++ header files not being found (e.g., when compiling target [libjpegturbo](https://github.com/google/fuzzer-test-suite/blob/master/libjpeg-turbo-07-2017/libjpeg_turbo_fuzzer.cc) it complains that the `memory` header file cannot be found). I am using LLVM 7.0.0.

After a bit of digging, I think it's because I am not using the LLVM C++ stdlib ( as described in this [doc](https://github.com/AngoraFuzzer/Angora/blob/master/docs/build_target.md#build-c-program-and-c-standard-library)).

I tried to run the compile.sh script and received the following error:

```
-- Check for working C compiler: /home/anngora/bin/angora-clang
-- Check for working C compiler: /home/angora/bin/angora-clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/angora/bin/angora-clang++
-- Check for working CXX compiler: /home/angora/bin/angora-clang++ -- broken
CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCXXCompiler.cmake:45 (message):
  The C++ compiler

    "/home/angora/bin/angora-clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/angora/build_track/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/ninja" "cmTC_8f865"
    [1/2] Building CXX object CMakeFiles/cmTC_8f865.dir/testCXXCompiler.cxx.o
    angora-llvm-pass
    [+] Fast Mode.
    ModName: testCXXCompiler.cxx -- 2709996875
    [2/2] Linking CXX executable cmTC_8f865
    FAILED: cmTC_8f865 
    : && /home/angora/bin/angora-clang++     CMakeFiles/cmTC_8f865.dir/testCXXCompiler.cxx.o  -o cmTC_8f865   && :
    ld: error: cannot find -lc++abi
    clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.
    
  CMake will not be able to correctly generate this project.
```

Am I misunderstanding how to compile C++ programs?

**Comment by spinpx** [comment]
Hi adrianherrera ,
Have you set 
```
export LD_LIBRARY_PATH=/path-to-clang/lib:$LD_LIBRARY_PATH
```

**Comment by adrianherrera** [comment]
Ah right, when I use your LLVM install script it works fine. It just wasn't working with my system LLVM. Thanks!
