### ISSUE TITLE
ARM

### ISSUE THREAD

**Issue by vanhauser-thc** [AngoraFuzzer/Angora#8]
not exactly an issue, more a question:

you specify amd64 as a requirement though llvm is used for compiling. with AFL, in llvm_mode it runs on any platform llvm is available. So I wonder if that is the same case with Angora?
I work for some projects on ARM environments so that would be useful to know.

**Comment by spinpx** [comment]
I am not sure. It depends on whether DFSAN supports it or not.

**Comment by vanhauser-thc** [comment]
ah damn: 

https://clang.llvm.org/docs/DataFlowSanitizer.html

"DataFlowSanitizer is a work in progress, currently under development for x86_64 Linux."

**Comment by vanhauser-thc** [comment]
taintgrind is a valgrind module, so it works differently, not directly on the assembly level but on an upheaved meta language (similar to llvm). I think in theory it could be used, but it would be a lot of, a hell lot of work and 2nd valgrind is super slow. I think only ptrace single stepping is slower :)
