### ISSUE TITLE
Setting total run time for fuzzer

### ISSUE THREAD

**Issue by Anjali05** [AngoraFuzzer/Angora#94]
Hi, 
I want to check if there is a way to set the overall time to run the fuzzer which I can pass as an argument?

I didn't find anything in the default options.

Thanks

**Comment by DataCorrupted** [comment]
We used to do `timeout <duration> <fuzzer-command>`. Maybe you can use that. See `man timeout`.

**Comment by Anjali05** [comment]
@DataCorrupted Whats a good overall time to run LAVA-M programs?

**Comment by DataCorrupted** [comment]
I believe the paper mentioned 1core, 5 hours per LAVA-M program.
