### ISSUE TITLE
Minor inconsistency in gradient descent

### ISSUE THREAD

**Issue by Luc-Veldhuis** [AngoraFuzzer/Angora#97]
At line https://github.com/AngoraFuzzer/Angora/blob/master/fuzzer/src/search/gd.rs#L219 there is a check for linearity if `f_minus != f0` however, when `f_minus < f0` is true, this check is still there:
https://github.com/AngoraFuzzer/Angora/blob/master/fuzzer/src/search/gd.rs#L224

I opened a PR here: https://github.com/AngoraFuzzer/Angora/pull/96

**Comment by spinpx** [comment]
Thanks , I have merged the PR.
